services:
  telegram_bot:
    env_file: .env
    container_name: telegram_bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MY_SECRET_VARIABLE: ${BOT_API_TOKEN}
      # sometimes the console won't show print messages,
      # using PYTHONUNBUFFERED: 1 can fix this
      PYTHONUNBUFFERED: 1